set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_VERSION 1)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

SET(CMAKE_C_COMPILER aarch64-unknown-linux-gnu-gcc)
SET(CMAKE_AR aarch64-unknown-linux-gnu-ar)
SET(CMAKE_STRIP aarch64-unknown-linux-gnu-strip)
SET(CMAKE_RANLIB aarch64-unknown-linux-gnu-ranlib)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
