FROM debian:buster
LABEL maintainer="Kleis Auke Wolthuizen <info@kleisauke.nl>"

# Create Debian-based container suitable for post-processing Windows binaries

RUN apt-get update && apt-get install -y advancecomp curl zip
