FROM debian:buster
LABEL maintainer "Kleis Auke Wolthuizen <info@kleisauke.nl>"

# Create Debian-based container suitable for post-processing Windows x64/x86 binaries

RUN apt-get update && apt-get install -y curl zip advancecomp
