name: CI Platform

on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'Platform to build (e.g., linux-x64, osx-arm64)'
        required: true
      os:
        description: 'Runner OS (e.g., ubuntu-24.04, macos-14)'
        required: true

permissions: {}

jobs:
  build:
    name: build-${{ github.event.inputs.platform }}
    runs-on: ${{ github.event.inputs.os }}
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download previously built Docker image
        if: github.event.inputs.platform == 'linux-arm'
        id: fetch-docker
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api repos/:owner/:repo/actions/artifacts \
            -q 'first(.artifacts|.[]|select(.name=="docker-${{ github.event.inputs.platform }}" and .expired==false)|.archive_download_url)' \
            | xargs gh api > tmp.zip || exit 0
          unzip tmp.zip
          rm tmp.zip
          echo "docker_file_name=docker-${{ github.event.inputs.platform }}.tar.gz" >> $GITHUB_OUTPUT

      - name: Load relevant image locally
        if: steps.fetch-docker.outputs.docker_file_name != ''
        run: docker load -i ${{ steps.fetch-docker.outputs.docker_file_name }} || echo "Could not load Docker image"

      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          pipx install meson==1.7.2
          brew install automake nasm python-packaging

      - name: Build ${{ github.event.inputs.platform }}
        run: ./build-exp.sh ${{ github.event.inputs.platform }}

      - name: Upload ${{ github.event.inputs.platform }} artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ github.event.inputs.platform }}
          path: libvips-*-${{ github.event.inputs.platform }}.tar.gz
          compression-level: 0
          retention-days: 1
          if-no-files-found: error

      - name: Save Docker image
        if: github.event.inputs.platform == 'linux-arm'
        run: docker save vips-dev-${{ github.event.inputs.platform }}:latest | gzip > docker-${{ github.event.inputs.platform }}.tar.gz

      - name: Upload Docker image as build artifact
        if: github.event.inputs.platform == 'linux-arm'
        uses: actions/upload-artifact@v4
        with:
          name: docker-${{ github.event.inputs.platform }}
          path: docker-${{ github.event.inputs.platform }}.tar.gz